name: Docker Build and Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag to build (e.g. v1.0.1)'
        required: true
  workflow_run:
    workflows: ["Auto Tag"]
    types:
      - completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get tag
        id: get-tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_run" ]; then
            echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
          else
            echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          fi

      - name: Create .env file
        run: |
          cp .env.example .env
          echo "ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" >> .env
          echo "TWITTER_USERNAME=${{ secrets.TWITTER_USERNAME }}" >> .env
          echo "TWITTER_PASSWORD=${{ secrets.TWITTER_PASSWORD }}" >> .env
          echo "TWITTER_EMAIL=${{ secrets.TWITTER_EMAIL }}" >> .env
          echo "TWITTER_COOKIES_AUTH_TOKEN=${{ secrets.TWITTER_COOKIES_AUTH_TOKEN }}" >> .env
          echo "TWITTER_COOKIES_CT0=${{ secrets.TWITTER_COOKIES_CT0 }}" >> .env
          echo "TWITTER_COOKIES_GUEST_ID=${{ secrets.TWITTER_COOKIES_GUEST_ID }}" >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          load: true
          tags: |
            438465133266.dkr.ecr.us-east-2.amazonaws.com/luuka:latest
            438465133266.dkr.ecr.us-east-2.amazonaws.com/luuka:${{ steps.get-tag.outputs.TAG }}

      - name: Push to ECR
        run: |
          docker push 438465133266.dkr.ecr.us-east-2.amazonaws.com/luuka:latest
          docker push 438465133266.dkr.ecr.us-east-2.amazonaws.com/luuka:${{ steps.get-tag.outputs.TAG }}

      - name: Force new ECS deployment
        run: |
          aws ecs update-service --cluster luuka-cluster --service luuka-service --force-new-deployment --region us-east-2